version: '3.8'

services:
  llm_with_rag:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./src:/app/src
