embedding_model: sentence-transformers/all-MiniLM-L6-v2
routing_model: chibao24/model_routing_few_shot
splitter_chunk_size: 500
splitter_chunk_overlap: 100

db_faiss_path: data/vectorstores/db_faiss/

custom_prompt_template_path: config/custom_prompt_template.txt
openai_max_tokens: 1024
# openai_model: gpt-3.5-turbo-instruct
openai_model: 
  0: gpt-3.5-turbo-instruct
  1: gpt-4o

openai_temperature: 0.9
k_similar: 5
lambda_mult: 0.7
search_type: mmr

