embedding_model: sentence-transformers/all-MiniLM-L6-v2
splitter_chunk_size: 256
splitter_chunk_overlap: 10

db_faiss_path: data/vectorstores/db_faiss/

custom_prompt_template_path: config/custom_prompt_template.txt
openai_max_tokens: 1024
# openai_model: gpt-3.5-turbo-instruct
openai_model: gpt-4o
openai_temperature: 0.9
k_similar: 3

