name: LLM and RAG system

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libreoffice 
        make install


    # - name: Run bot tests
    #   run: make bot

    - name: Run ingest data
      run: python src/ingest.py


